version: '3'

services:
  app:
    build: ./
    image: typescript-docker-express
    restart: always
    volumes: &appvolumes
      - ./:/app:delegated
    ports:
      - '3000:3000'
    environment: &appenv
      PORT: 3000

  app_watcher:
    build: ./
    image: typescript-docker-express
    depends_on:
      - app
    restart: always
    volumes: *appvolumes
    environment: *appenv
    command:
      ['pm2-runtime', 'start', 'ecosystem.config.js', '--only=app-watcher']
